version: 2
jobs:
    build:
        working_directory: ~/devel

        docker:
            - image: circleci/node:8

        steps:
            - checkout

            - run:
                  name: Update System Dependencies
                  command: |
                      sudo apt-get update
                      sudo apt-get upgrade -y

            - restore_cache:
                  key: dependency-cache-{{ checksum "package.json" }}

            - run:
                  name: Install Dependencies
                  command: npm ci --only=production

            - save_cache:
                  key: dependency-cache-{{ checksum "package.json" }}
                  paths:
                      - ./node_modules

            - run:
                  name: Run Tests
                  command: npm test

            - store_artifacts:
                  path: coverage
                  prefix: coverage
